# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/nikgal/Vivado/fpga_in_the_loop/fpga_test_initialize_0/fpga_test_initialize_0.xci
# IP: The module: 'fpga_test_initialize_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nikgal/Vivado/fpga_in_the_loop/fpga_test_initialize_0/constraints/fpga_test_initialize_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_test_initialize_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/nikgal/Vivado/fpga_in_the_loop/fpga_test_initialize_0/fpga_test_initialize_0.xci
# IP: The module: 'fpga_test_initialize_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nikgal/Vivado/fpga_in_the_loop/fpga_test_initialize_0/constraints/fpga_test_initialize_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_test_initialize_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
