// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fpga_test_initialize_fpga_test_initialize,hls_ip_2023_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=50000.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.181000,HLS_SYN_LAT=14,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=235,HLS_SYN_LUT=410,HLS_VERSION=2023_1}" *)

module fpga_test_initialize (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_fpga_test_B_AC,
        p_fpga_test_B_AC_ap_vld,
        p_fpga_test_B_StateSpace_o1_address0,
        p_fpga_test_B_StateSpace_o1_ce0,
        p_fpga_test_B_StateSpace_o1_we0,
        p_fpga_test_B_StateSpace_o1_d0,
        p_fpga_test_B_StateSpace_o1_address1,
        p_fpga_test_B_StateSpace_o1_ce1,
        p_fpga_test_B_StateSpace_o1_we1,
        p_fpga_test_B_StateSpace_o1_d1,
        p_fpga_test_B_StateSpace_o2,
        p_fpga_test_B_StateSpace_o2_ap_vld,
        p_fpga_test_B_DataTypeConversion2,
        p_fpga_test_B_DataTypeConversion2_ap_vld,
        p_fpga_test_B_LookUpTable,
        p_fpga_test_B_LookUpTable_ap_vld,
        p_fpga_test_B_IC,
        p_fpga_test_B_IC_ap_vld,
        p_fpga_test_B_Derivative,
        p_fpga_test_B_Derivative_ap_vld,
        p_fpga_test_B_DataTypeConversion1,
        p_fpga_test_B_DataTypeConversion1_ap_vld,
        p_fpga_test_DW_DelayTs_DSTATE,
        p_fpga_test_DW_DelayTs_DSTATE_ap_vld,
        p_fpga_test_DW_DelayTs_DSTATE_f,
        p_fpga_test_DW_DelayTs_DSTATE_f_ap_vld,
        p_fpga_test_DW_IC_FirstOutputTime,
        p_fpga_test_DW_IC_FirstOutputTime_ap_vld,
        p_fpga_test_DW_TimeStampA,
        p_fpga_test_DW_TimeStampA_ap_vld,
        p_fpga_test_DW_LastUAtTimeA,
        p_fpga_test_DW_LastUAtTimeA_ap_vld,
        p_fpga_test_DW_TimeStampB,
        p_fpga_test_DW_TimeStampB_ap_vld,
        p_fpga_test_DW_LastUAtTimeB,
        p_fpga_test_DW_LastUAtTimeB_ap_vld,
        p_fpga_test_DW_StateSpace_PWORK,
        p_fpga_test_DW_StateSpace_PWORK_ap_vld,
        p_fpga_test_DW_StateSpace_IWORK_address0,
        p_fpga_test_DW_StateSpace_IWORK_ce0,
        p_fpga_test_DW_StateSpace_IWORK_we0,
        p_fpga_test_DW_StateSpace_IWORK_d0,
        p_fpga_test_DW_StateSpace_IWORK_address1,
        p_fpga_test_DW_StateSpace_IWORK_ce1,
        p_fpga_test_DW_StateSpace_IWORK_we1,
        p_fpga_test_DW_StateSpace_IWORK_d1,
        p_fpga_test_DW_u5_Mode,
        p_fpga_test_DW_u5_Mode_ap_vld,
        p_fpga_test_M,
        p_fpga_test_M_ap_vld
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] p_fpga_test_B_AC;
output   p_fpga_test_B_AC_ap_vld;
output  [0:0] p_fpga_test_B_StateSpace_o1_address0;
output   p_fpga_test_B_StateSpace_o1_ce0;
output   p_fpga_test_B_StateSpace_o1_we0;
output  [63:0] p_fpga_test_B_StateSpace_o1_d0;
output  [0:0] p_fpga_test_B_StateSpace_o1_address1;
output   p_fpga_test_B_StateSpace_o1_ce1;
output   p_fpga_test_B_StateSpace_o1_we1;
output  [63:0] p_fpga_test_B_StateSpace_o1_d1;
output  [63:0] p_fpga_test_B_StateSpace_o2;
output   p_fpga_test_B_StateSpace_o2_ap_vld;
output  [63:0] p_fpga_test_B_DataTypeConversion2;
output   p_fpga_test_B_DataTypeConversion2_ap_vld;
output  [63:0] p_fpga_test_B_LookUpTable;
output   p_fpga_test_B_LookUpTable_ap_vld;
output  [63:0] p_fpga_test_B_IC;
output   p_fpga_test_B_IC_ap_vld;
output  [63:0] p_fpga_test_B_Derivative;
output   p_fpga_test_B_Derivative_ap_vld;
output  [7:0] p_fpga_test_B_DataTypeConversion1;
output   p_fpga_test_B_DataTypeConversion1_ap_vld;
output  [63:0] p_fpga_test_DW_DelayTs_DSTATE;
output   p_fpga_test_DW_DelayTs_DSTATE_ap_vld;
output  [63:0] p_fpga_test_DW_DelayTs_DSTATE_f;
output   p_fpga_test_DW_DelayTs_DSTATE_f_ap_vld;
output  [63:0] p_fpga_test_DW_IC_FirstOutputTime;
output   p_fpga_test_DW_IC_FirstOutputTime_ap_vld;
output  [63:0] p_fpga_test_DW_TimeStampA;
output   p_fpga_test_DW_TimeStampA_ap_vld;
output  [63:0] p_fpga_test_DW_LastUAtTimeA;
output   p_fpga_test_DW_LastUAtTimeA_ap_vld;
output  [63:0] p_fpga_test_DW_TimeStampB;
output   p_fpga_test_DW_TimeStampB_ap_vld;
output  [63:0] p_fpga_test_DW_LastUAtTimeB;
output   p_fpga_test_DW_LastUAtTimeB_ap_vld;
output  [831:0] p_fpga_test_DW_StateSpace_PWORK;
output   p_fpga_test_DW_StateSpace_PWORK_ap_vld;
output  [3:0] p_fpga_test_DW_StateSpace_IWORK_address0;
output   p_fpga_test_DW_StateSpace_IWORK_ce0;
output   p_fpga_test_DW_StateSpace_IWORK_we0;
output  [31:0] p_fpga_test_DW_StateSpace_IWORK_d0;
output  [3:0] p_fpga_test_DW_StateSpace_IWORK_address1;
output   p_fpga_test_DW_StateSpace_IWORK_ce1;
output   p_fpga_test_DW_StateSpace_IWORK_we1;
output  [31:0] p_fpga_test_DW_StateSpace_IWORK_d1;
output  [7:0] p_fpga_test_DW_u5_Mode;
output   p_fpga_test_DW_u5_Mode_ap_vld;
output  [519:0] p_fpga_test_M;
output   p_fpga_test_M_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_fpga_test_B_AC_ap_vld;
reg p_fpga_test_B_StateSpace_o1_ce0;
reg p_fpga_test_B_StateSpace_o1_we0;
reg p_fpga_test_B_StateSpace_o1_ce1;
reg p_fpga_test_B_StateSpace_o1_we1;
reg p_fpga_test_B_StateSpace_o2_ap_vld;
reg p_fpga_test_B_DataTypeConversion2_ap_vld;
reg p_fpga_test_B_LookUpTable_ap_vld;
reg p_fpga_test_B_IC_ap_vld;
reg p_fpga_test_B_Derivative_ap_vld;
reg p_fpga_test_B_DataTypeConversion1_ap_vld;
reg p_fpga_test_DW_DelayTs_DSTATE_ap_vld;
reg p_fpga_test_DW_DelayTs_DSTATE_f_ap_vld;
reg p_fpga_test_DW_IC_FirstOutputTime_ap_vld;
reg p_fpga_test_DW_TimeStampA_ap_vld;
reg p_fpga_test_DW_LastUAtTimeA_ap_vld;
reg p_fpga_test_DW_TimeStampB_ap_vld;
reg p_fpga_test_DW_LastUAtTimeB_ap_vld;
reg p_fpga_test_DW_StateSpace_PWORK_ap_vld;
reg[3:0] p_fpga_test_DW_StateSpace_IWORK_address0;
reg p_fpga_test_DW_StateSpace_IWORK_ce0;
reg p_fpga_test_DW_StateSpace_IWORK_we0;
reg[3:0] p_fpga_test_DW_StateSpace_IWORK_address1;
reg p_fpga_test_DW_StateSpace_IWORK_ce1;
reg p_fpga_test_DW_StateSpace_IWORK_we1;
reg p_fpga_test_DW_u5_Mode_ap_vld;
reg p_fpga_test_M_ap_vld;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] add_ln90_fu_463_p2;
reg   [1:0] add_ln90_reg_660;
wire    ap_CS_fsm_state2;
wire   [0:0] empty_fu_469_p1;
reg   [0:0] empty_reg_665;
wire   [0:0] icmp_ln90_fu_457_p2;
wire   [1:0] add_ln91_fu_479_p2;
wire    ap_CS_fsm_state3;
reg   [1:0] j_reg_418;
wire   [0:0] icmp_ln91_fu_473_p2;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg   [1:0] i_fu_124;
reg   [63:0] fpga_test_DW_StateSpace_PWORK_DS_3_fu_128;
wire   [63:0] fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3;
wire   [1:0] add_ln92_1_fu_544_p3;
reg   [63:0] fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132;
reg   [63:0] fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136;
reg   [63:0] fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140;
wire   [0:0] trunc_ln92_fu_485_p1;
wire   [1:0] add_ln_fu_489_p3;
wire   [0:0] icmp_ln9_fu_496_p2;
wire   [0:0] icmp_ln9_2_fu_516_p2;
wire   [0:0] icmp_ln9_1_fu_510_p2;
wire   [0:0] empty_8_fu_530_p2;
wire   [63:0] select_ln9_1_i_fu_522_p3;
wire   [63:0] select_ln9_fu_502_p3;
wire   [63:0] empty_12_fu_599_p1;
wire   [63:0] empty_11_fu_595_p1;
wire   [63:0] empty_10_fu_591_p1;
wire   [63:0] empty_9_fu_587_p1;
wire   [800:0] p_partset_fu_603_p6;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[0] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[2] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[3] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[4] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[5] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[6] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[7] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[8] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[9] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[10] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[11] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[13] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[14] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[16] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[18] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[19] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[20] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[21] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[24] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[25] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[26] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[29] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[30] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[31] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[32] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[33] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[34] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[35] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[36] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[37] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[38] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[39] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[40] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[41] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[42] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[43] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[44] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[45] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[46] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[47] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[48] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[49] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[50] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[51] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[52] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[53] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[54] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[55] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[56] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[57] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[58] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[59] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[60] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[61] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[63] <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (2'd1 == add_ln92_1_fu_544_p3) & (icmp_ln91_fu_473_p2 == 1'd0))) begin
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[0] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[0];
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[11 : 2] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[11 : 2];
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[14 : 13] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[14 : 13];
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[16] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[16];
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[21 : 18] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[21 : 18];
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[26 : 24] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[26 : 24];
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[61 : 29] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[61 : 29];
        fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[63] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[63];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[0] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[2] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[3] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[4] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[5] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[6] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[7] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[8] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[9] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[10] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[11] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[13] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[14] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[16] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[18] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[19] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[20] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[21] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[24] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[25] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[26] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[29] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[30] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[31] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[32] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[33] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[34] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[35] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[36] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[37] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[38] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[39] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[40] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[41] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[42] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[43] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[44] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[45] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[46] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[47] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[48] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[49] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[50] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[51] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[52] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[53] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[54] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[55] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[56] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[57] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[58] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[59] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[60] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[61] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[63] <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (2'd2 == add_ln92_1_fu_544_p3) & (icmp_ln91_fu_473_p2 == 1'd0))) begin
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[0] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[0];
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[11 : 2] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[11 : 2];
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[14 : 13] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[14 : 13];
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[16] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[16];
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[21 : 18] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[21 : 18];
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[26 : 24] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[26 : 24];
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[61 : 29] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[61 : 29];
        fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[63] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[63];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[0] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[2] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[3] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[4] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[5] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[6] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[7] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[8] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[9] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[10] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[11] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[13] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[14] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[16] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[18] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[19] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[20] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[21] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[24] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[25] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[26] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[29] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[30] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[31] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[32] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[33] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[34] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[35] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[36] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[37] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[38] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[39] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[40] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[41] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[42] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[43] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[44] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[45] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[46] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[47] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[48] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[49] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[50] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[51] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[52] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[53] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[54] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[55] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[56] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[57] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[58] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[59] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[60] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[61] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[63] <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (2'd3 == add_ln92_1_fu_544_p3) & (icmp_ln91_fu_473_p2 == 1'd0))) begin
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[0] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[0];
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[11 : 2] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[11 : 2];
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[14 : 13] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[14 : 13];
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[16] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[16];
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[21 : 18] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[21 : 18];
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[26 : 24] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[26 : 24];
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[61 : 29] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[61 : 29];
        fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[63] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[63];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[0] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[2] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[3] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[4] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[5] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[6] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[7] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[8] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[9] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[10] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[11] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[13] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[14] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[16] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[18] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[19] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[20] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[21] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[24] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[25] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[26] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[29] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[30] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[31] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[32] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[33] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[34] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[35] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[36] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[37] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[38] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[39] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[40] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[41] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[42] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[43] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[44] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[45] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[46] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[47] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[48] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[49] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[50] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[51] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[52] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[53] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[54] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[55] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[56] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[57] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[58] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[59] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[60] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[61] <= 1'b0;
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[63] <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln91_fu_473_p2 == 1'd0) & (2'd0 == add_ln92_1_fu_544_p3))) begin
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[0] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[0];
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[11 : 2] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[11 : 2];
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[14 : 13] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[14 : 13];
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[16] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[16];
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[21 : 18] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[21 : 18];
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[26 : 24] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[26 : 24];
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[61 : 29] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[61 : 29];
        fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[63] <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3[63];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_124 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln91_fu_473_p2 == 1'd1))) begin
        i_fu_124 <= add_ln90_reg_660;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln91_fu_473_p2 == 1'd0))) begin
        j_reg_418 <= add_ln91_fu_479_p2;
    end else if (((icmp_ln90_fu_457_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_reg_418 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln90_reg_660 <= add_ln90_fu_463_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln90_fu_457_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        empty_reg_665 <= empty_fu_469_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_B_AC_ap_vld = 1'b1;
    end else begin
        p_fpga_test_B_AC_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_B_DataTypeConversion1_ap_vld = 1'b1;
    end else begin
        p_fpga_test_B_DataTypeConversion1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_B_DataTypeConversion2_ap_vld = 1'b1;
    end else begin
        p_fpga_test_B_DataTypeConversion2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_B_Derivative_ap_vld = 1'b1;
    end else begin
        p_fpga_test_B_Derivative_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_B_IC_ap_vld = 1'b1;
    end else begin
        p_fpga_test_B_IC_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_B_LookUpTable_ap_vld = 1'b1;
    end else begin
        p_fpga_test_B_LookUpTable_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_B_StateSpace_o1_ce0 = 1'b1;
    end else begin
        p_fpga_test_B_StateSpace_o1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_B_StateSpace_o1_ce1 = 1'b1;
    end else begin
        p_fpga_test_B_StateSpace_o1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_B_StateSpace_o1_we0 = 1'b1;
    end else begin
        p_fpga_test_B_StateSpace_o1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_B_StateSpace_o1_we1 = 1'b1;
    end else begin
        p_fpga_test_B_StateSpace_o1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_B_StateSpace_o2_ap_vld = 1'b1;
    end else begin
        p_fpga_test_B_StateSpace_o2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_DW_DelayTs_DSTATE_ap_vld = 1'b1;
    end else begin
        p_fpga_test_DW_DelayTs_DSTATE_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_DW_DelayTs_DSTATE_f_ap_vld = 1'b1;
    end else begin
        p_fpga_test_DW_DelayTs_DSTATE_f_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_DW_IC_FirstOutputTime_ap_vld = 1'b1;
    end else begin
        p_fpga_test_DW_IC_FirstOutputTime_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_DW_LastUAtTimeA_ap_vld = 1'b1;
    end else begin
        p_fpga_test_DW_LastUAtTimeA_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_DW_LastUAtTimeB_ap_vld = 1'b1;
    end else begin
        p_fpga_test_DW_LastUAtTimeB_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_DW_StateSpace_IWORK_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        p_fpga_test_DW_StateSpace_IWORK_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_fpga_test_DW_StateSpace_IWORK_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        p_fpga_test_DW_StateSpace_IWORK_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_fpga_test_DW_StateSpace_IWORK_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_fpga_test_DW_StateSpace_IWORK_address0 = 64'd0;
    end else begin
        p_fpga_test_DW_StateSpace_IWORK_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_DW_StateSpace_IWORK_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        p_fpga_test_DW_StateSpace_IWORK_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_fpga_test_DW_StateSpace_IWORK_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        p_fpga_test_DW_StateSpace_IWORK_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_fpga_test_DW_StateSpace_IWORK_address1 = 64'd1;
    end else begin
        p_fpga_test_DW_StateSpace_IWORK_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        p_fpga_test_DW_StateSpace_IWORK_ce0 = 1'b1;
    end else begin
        p_fpga_test_DW_StateSpace_IWORK_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        p_fpga_test_DW_StateSpace_IWORK_ce1 = 1'b1;
    end else begin
        p_fpga_test_DW_StateSpace_IWORK_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln90_fu_457_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        p_fpga_test_DW_StateSpace_IWORK_we0 = 1'b1;
    end else begin
        p_fpga_test_DW_StateSpace_IWORK_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        p_fpga_test_DW_StateSpace_IWORK_we1 = 1'b1;
    end else begin
        p_fpga_test_DW_StateSpace_IWORK_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_DW_StateSpace_PWORK_ap_vld = 1'b1;
    end else begin
        p_fpga_test_DW_StateSpace_PWORK_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_DW_TimeStampA_ap_vld = 1'b1;
    end else begin
        p_fpga_test_DW_TimeStampA_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_DW_TimeStampB_ap_vld = 1'b1;
    end else begin
        p_fpga_test_DW_TimeStampB_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_DW_u5_Mode_ap_vld = 1'b1;
    end else begin
        p_fpga_test_DW_u5_Mode_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_fpga_test_M_ap_vld = 1'b1;
    end else begin
        p_fpga_test_M_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln90_fu_457_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln91_fu_473_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln90_fu_463_p2 = (i_fu_124 + 2'd1);

assign add_ln91_fu_479_p2 = (j_reg_418 + 2'd1);

assign add_ln92_1_fu_544_p3 = {{empty_reg_665}, {trunc_ln92_fu_485_p1}};

assign add_ln_fu_489_p3 = {{trunc_ln92_fu_485_p1}, {empty_reg_665}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign empty_10_fu_591_p1 = fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132;

assign empty_11_fu_595_p1 = fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136;

assign empty_12_fu_599_p1 = fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140;

assign empty_8_fu_530_p2 = (icmp_ln9_2_fu_516_p2 | icmp_ln9_1_fu_510_p2);

assign empty_9_fu_587_p1 = fpga_test_DW_StateSpace_PWORK_DS_3_fu_128;

assign empty_fu_469_p1 = i_fu_124[0:0];

assign fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3 = ((empty_8_fu_530_p2[0:0] == 1'b1) ? select_ln9_1_i_fu_522_p3 : select_ln9_fu_502_p3);

assign icmp_ln90_fu_457_p2 = ((i_fu_124 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln91_fu_473_p2 = ((j_reg_418 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln9_1_fu_510_p2 = ((add_ln_fu_489_p3 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln9_2_fu_516_p2 = ((add_ln_fu_489_p3 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_496_p2 = ((add_ln_fu_489_p3 == 2'd0) ? 1'b1 : 1'b0);

assign p_fpga_test_B_AC = 32'd0;

assign p_fpga_test_B_DataTypeConversion1 = 8'd0;

assign p_fpga_test_B_DataTypeConversion2 = 64'd0;

assign p_fpga_test_B_Derivative = 64'd0;

assign p_fpga_test_B_IC = 64'd0;

assign p_fpga_test_B_LookUpTable = 64'd0;

assign p_fpga_test_B_StateSpace_o1_address0 = 64'd1;

assign p_fpga_test_B_StateSpace_o1_address1 = 64'd0;

assign p_fpga_test_B_StateSpace_o1_d0 = 64'd0;

assign p_fpga_test_B_StateSpace_o1_d1 = 64'd0;

assign p_fpga_test_B_StateSpace_o2 = 64'd0;

assign p_fpga_test_DW_DelayTs_DSTATE = 64'd0;

assign p_fpga_test_DW_DelayTs_DSTATE_f = 64'd0;

assign p_fpga_test_DW_IC_FirstOutputTime = 64'd0;

assign p_fpga_test_DW_LastUAtTimeA = 64'd0;

assign p_fpga_test_DW_LastUAtTimeB = 64'd0;

assign p_fpga_test_DW_StateSpace_IWORK_d0 = 32'd0;

assign p_fpga_test_DW_StateSpace_IWORK_d1 = 32'd0;

assign p_fpga_test_DW_StateSpace_PWORK = $signed(p_partset_fu_603_p6);

assign p_fpga_test_DW_TimeStampA = 64'd0;

assign p_fpga_test_DW_TimeStampB = 64'd0;

assign p_fpga_test_DW_u5_Mode = 8'd0;

assign p_fpga_test_M = 520'd86815797374950692418404905996504044193783126233561631201648090270059263426560;

assign p_partset_fu_603_p6 = {{{{{{{{545'd57586096600338689777602158661574072407183880421377311071403670977201035089204048551991702482145558332283083210285790945677118972826262043335725264193408947544129536}, {empty_12_fu_599_p1}}}, {empty_11_fu_595_p1}}}, {empty_10_fu_591_p1}}}, {empty_9_fu_587_p1}};

assign select_ln9_1_i_fu_522_p3 = ((icmp_ln9_2_fu_516_p2[0:0] == 1'b1) ? 64'd4607182409792827160 : 64'd4607182409792827161);

assign select_ln9_fu_502_p3 = ((icmp_ln9_fu_496_p2[0:0] == 1'b1) ? 64'd13830554446647602969 : 64'd4517329188385744877);

assign trunc_ln92_fu_485_p1 = j_reg_418[0:0];

always @ (posedge ap_clk) begin
    fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[1] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[12:12] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[15:15] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[17:17] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[23:22] <= 2'b00;
    fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[28:27] <= 2'b00;
    fpga_test_DW_StateSpace_PWORK_DS_3_fu_128[62] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[1] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[12:12] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[15:15] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[17:17] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[23:22] <= 2'b00;
    fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[28:27] <= 2'b00;
    fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132[62] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[1] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[12:12] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[15:15] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[17:17] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[23:22] <= 2'b00;
    fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[28:27] <= 2'b00;
    fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136[62] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[1] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[12:12] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[15:15] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[17:17] <= 1'b0;
    fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[23:22] <= 2'b00;
    fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[28:27] <= 2'b00;
    fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140[62] <= 1'b0;
end

endmodule //fpga_test_initialize
