# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/my_const.xdc

# IP: C:/Users/nikgal/Vivado/fpga_in_the_loop/fpga_test_step_0/fpga_test_step_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_test_step_0 || ORIG_REF_NAME==fpga_test_step_0} -quiet] -quiet
