-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fpga_test_initialize is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_fpga_test_B_AC : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_fpga_test_B_AC_ap_vld : OUT STD_LOGIC;
    p_fpga_test_B_StateSpace_o1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_fpga_test_B_StateSpace_o1_ce0 : OUT STD_LOGIC;
    p_fpga_test_B_StateSpace_o1_we0 : OUT STD_LOGIC;
    p_fpga_test_B_StateSpace_o1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_fpga_test_B_StateSpace_o1_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_fpga_test_B_StateSpace_o1_ce1 : OUT STD_LOGIC;
    p_fpga_test_B_StateSpace_o1_we1 : OUT STD_LOGIC;
    p_fpga_test_B_StateSpace_o1_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_fpga_test_B_StateSpace_o2 : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_fpga_test_B_StateSpace_o2_ap_vld : OUT STD_LOGIC;
    p_fpga_test_B_DataTypeConversion2 : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_fpga_test_B_DataTypeConversion2_ap_vld : OUT STD_LOGIC;
    p_fpga_test_B_LookUpTable : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_fpga_test_B_LookUpTable_ap_vld : OUT STD_LOGIC;
    p_fpga_test_B_IC : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_fpga_test_B_IC_ap_vld : OUT STD_LOGIC;
    p_fpga_test_B_Derivative : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_fpga_test_B_Derivative_ap_vld : OUT STD_LOGIC;
    p_fpga_test_B_DataTypeConversion1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_fpga_test_B_DataTypeConversion1_ap_vld : OUT STD_LOGIC;
    p_fpga_test_DW_DelayTs_DSTATE : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_fpga_test_DW_DelayTs_DSTATE_ap_vld : OUT STD_LOGIC;
    p_fpga_test_DW_DelayTs_DSTATE_f : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_fpga_test_DW_DelayTs_DSTATE_f_ap_vld : OUT STD_LOGIC;
    p_fpga_test_DW_IC_FirstOutputTime : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_fpga_test_DW_IC_FirstOutputTime_ap_vld : OUT STD_LOGIC;
    p_fpga_test_DW_TimeStampA : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_fpga_test_DW_TimeStampA_ap_vld : OUT STD_LOGIC;
    p_fpga_test_DW_LastUAtTimeA : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_fpga_test_DW_LastUAtTimeA_ap_vld : OUT STD_LOGIC;
    p_fpga_test_DW_TimeStampB : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_fpga_test_DW_TimeStampB_ap_vld : OUT STD_LOGIC;
    p_fpga_test_DW_LastUAtTimeB : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_fpga_test_DW_LastUAtTimeB_ap_vld : OUT STD_LOGIC;
    p_fpga_test_DW_StateSpace_PWORK : OUT STD_LOGIC_VECTOR (831 downto 0);
    p_fpga_test_DW_StateSpace_PWORK_ap_vld : OUT STD_LOGIC;
    p_fpga_test_DW_StateSpace_IWORK_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    p_fpga_test_DW_StateSpace_IWORK_ce0 : OUT STD_LOGIC;
    p_fpga_test_DW_StateSpace_IWORK_we0 : OUT STD_LOGIC;
    p_fpga_test_DW_StateSpace_IWORK_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_fpga_test_DW_StateSpace_IWORK_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    p_fpga_test_DW_StateSpace_IWORK_ce1 : OUT STD_LOGIC;
    p_fpga_test_DW_StateSpace_IWORK_we1 : OUT STD_LOGIC;
    p_fpga_test_DW_StateSpace_IWORK_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_fpga_test_DW_u5_Mode : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_fpga_test_DW_u5_Mode_ap_vld : OUT STD_LOGIC;
    p_fpga_test_M : OUT STD_LOGIC_VECTOR (519 downto 0);
    p_fpga_test_M_ap_vld : OUT STD_LOGIC );
end;


architecture behav of fpga_test_initialize is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fpga_test_initialize_fpga_test_initialize,hls_ip_2023_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=50000.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.181000,HLS_SYN_LAT=14,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=235,HLS_SYN_LUT=410,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv64_8 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv64_9 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001001";
    constant ap_const_lv64_A : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001010";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv520_lc_1 : STD_LOGIC_VECTOR (519 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001011111111110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000111111000110100011011011100010111010110001110001000011001011010000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_BFEFFFFDE7212F19 : STD_LOGIC_VECTOR (63 downto 0) := "1011111111101111111111111111110111100111001000010010111100011001";
    constant ap_const_lv64_3EB0C6F6873C67ED : STD_LOGIC_VECTOR (63 downto 0) := "0011111010110000110001101111011010000111001111000110011111101101";
    constant ap_const_lv64_3FEFFFFDE7212F18 : STD_LOGIC_VECTOR (63 downto 0) := "0011111111101111111111111111110111100111001000010010111100011000";
    constant ap_const_lv64_3FEFFFFDE7212F19 : STD_LOGIC_VECTOR (63 downto 0) := "0011111111101111111111111111110111100111001000010010111100011001";
    constant ap_const_lv545_lc_2 : STD_LOGIC_VECTOR (544 downto 0) := "10000000000000000000000000000001001000000010110010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal add_ln90_fu_463_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln90_reg_660 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal empty_fu_469_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_665 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_fu_457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln91_fu_479_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal j_reg_418 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln91_fu_473_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal i_fu_124 : STD_LOGIC_VECTOR (1 downto 0);
    signal fpga_test_DW_StateSpace_PWORK_DS_3_fu_128 : STD_LOGIC_VECTOR (63 downto 0);
    signal fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln92_1_fu_544_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132 : STD_LOGIC_VECTOR (63 downto 0);
    signal fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136 : STD_LOGIC_VECTOR (63 downto 0);
    signal fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln92_fu_485_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln_fu_489_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln9_fu_496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_2_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_1_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_8_fu_530_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_1_i_fu_522_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln9_fu_502_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_12_fu_599_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_11_fu_595_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_10_fu_591_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_9_fu_587_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_partset_fu_603_p6 : STD_LOGIC_VECTOR (800 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(0) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(2) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(3) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(4) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(5) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(6) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(7) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(8) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(9) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(10) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(11) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(13) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(14) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(16) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(18) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(19) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(20) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(21) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(24) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(25) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(26) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(29) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(30) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(31) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(32) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(33) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(34) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(35) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(36) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(37) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(38) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(39) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(40) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(41) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(42) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(43) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(44) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(45) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(46) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(47) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(48) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(49) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(50) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(51) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(52) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(53) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(54) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(55) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(56) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(57) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(58) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(59) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(60) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(61) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(63) <= '0';
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv2_1 = add_ln92_1_fu_544_p3) and (icmp_ln91_fu_473_p2 = ap_const_lv1_0))) then 
                                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(0) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(0);                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(11 downto 2) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(11 downto 2);                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(14 downto 13) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(14 downto 13);                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(16) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(16);                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(21 downto 18) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(21 downto 18);                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(26 downto 24) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(26 downto 24);                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(61 downto 29) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(61 downto 29);                fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(63) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(63);
            end if; 
        end if;
    end process;

    fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(0) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(2) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(3) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(4) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(5) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(6) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(7) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(8) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(9) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(10) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(11) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(13) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(14) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(16) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(18) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(19) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(20) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(21) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(24) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(25) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(26) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(29) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(30) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(31) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(32) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(33) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(34) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(35) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(36) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(37) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(38) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(39) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(40) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(41) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(42) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(43) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(44) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(45) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(46) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(47) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(48) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(49) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(50) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(51) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(52) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(53) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(54) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(55) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(56) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(57) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(58) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(59) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(60) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(61) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(63) <= '0';
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv2_2 = add_ln92_1_fu_544_p3) and (icmp_ln91_fu_473_p2 = ap_const_lv1_0))) then 
                                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(0) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(0);                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(11 downto 2) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(11 downto 2);                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(14 downto 13) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(14 downto 13);                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(16) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(16);                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(21 downto 18) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(21 downto 18);                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(26 downto 24) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(26 downto 24);                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(61 downto 29) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(61 downto 29);                fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(63) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(63);
            end if; 
        end if;
    end process;

    fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(0) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(2) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(3) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(4) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(5) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(6) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(7) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(8) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(9) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(10) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(11) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(13) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(14) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(16) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(18) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(19) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(20) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(21) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(24) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(25) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(26) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(29) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(30) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(31) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(32) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(33) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(34) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(35) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(36) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(37) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(38) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(39) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(40) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(41) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(42) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(43) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(44) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(45) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(46) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(47) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(48) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(49) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(50) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(51) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(52) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(53) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(54) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(55) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(56) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(57) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(58) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(59) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(60) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(61) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(63) <= '0';
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv2_3 = add_ln92_1_fu_544_p3) and (icmp_ln91_fu_473_p2 = ap_const_lv1_0))) then 
                                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(0) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(0);                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(11 downto 2) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(11 downto 2);                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(14 downto 13) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(14 downto 13);                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(16) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(16);                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(21 downto 18) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(21 downto 18);                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(26 downto 24) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(26 downto 24);                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(61 downto 29) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(61 downto 29);                fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(63) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(63);
            end if; 
        end if;
    end process;

    fpga_test_DW_StateSpace_PWORK_DS_3_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(0) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(2) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(3) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(4) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(5) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(6) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(7) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(8) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(9) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(10) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(11) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(13) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(14) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(16) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(18) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(19) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(20) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(21) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(24) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(25) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(26) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(29) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(30) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(31) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(32) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(33) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(34) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(35) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(36) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(37) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(38) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(39) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(40) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(41) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(42) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(43) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(44) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(45) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(46) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(47) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(48) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(49) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(50) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(51) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(52) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(53) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(54) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(55) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(56) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(57) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(58) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(59) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(60) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(61) <= '0';
                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(63) <= '0';
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln91_fu_473_p2 = ap_const_lv1_0) and (ap_const_lv2_0 = add_ln92_1_fu_544_p3))) then 
                                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(0) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(0);                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(11 downto 2) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(11 downto 2);                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(14 downto 13) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(14 downto 13);                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(16) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(16);                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(21 downto 18) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(21 downto 18);                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(26 downto 24) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(26 downto 24);                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(61 downto 29) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(61 downto 29);                fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(63) <= fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3(63);
            end if; 
        end if;
    end process;

    i_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_fu_124 <= ap_const_lv2_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln91_fu_473_p2 = ap_const_lv1_1))) then 
                i_fu_124 <= add_ln90_reg_660;
            end if; 
        end if;
    end process;

    j_reg_418_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln91_fu_473_p2 = ap_const_lv1_0))) then 
                j_reg_418 <= add_ln91_fu_479_p2;
            elsif (((icmp_ln90_fu_457_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_reg_418 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln90_reg_660 <= add_ln90_fu_463_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln90_fu_457_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                empty_reg_665 <= empty_fu_469_p1;
            end if;
        end if;
    end process;
    fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(1) <= '0';
    fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(12 downto 12) <= "0";
    fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(15 downto 15) <= "0";
    fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(17 downto 17) <= "0";
    fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(23 downto 22) <= "00";
    fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(28 downto 27) <= "00";
    fpga_test_DW_StateSpace_PWORK_DS_3_fu_128(62) <= '0';
    fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(1) <= '0';
    fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(12 downto 12) <= "0";
    fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(15 downto 15) <= "0";
    fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(17 downto 17) <= "0";
    fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(23 downto 22) <= "00";
    fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(28 downto 27) <= "00";
    fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132(62) <= '0';
    fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(1) <= '0';
    fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(12 downto 12) <= "0";
    fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(15 downto 15) <= "0";
    fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(17 downto 17) <= "0";
    fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(23 downto 22) <= "00";
    fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(28 downto 27) <= "00";
    fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136(62) <= '0';
    fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(1) <= '0';
    fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(12 downto 12) <= "0";
    fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(15 downto 15) <= "0";
    fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(17 downto 17) <= "0";
    fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(23 downto 22) <= "00";
    fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(28 downto 27) <= "00";
    fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140(62) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln90_fu_457_p2, ap_CS_fsm_state3, icmp_ln91_fu_473_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln90_fu_457_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln91_fu_473_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln90_fu_463_p2 <= std_logic_vector(unsigned(i_fu_124) + unsigned(ap_const_lv2_1));
    add_ln91_fu_479_p2 <= std_logic_vector(unsigned(j_reg_418) + unsigned(ap_const_lv2_1));
    add_ln92_1_fu_544_p3 <= (empty_reg_665 & trunc_ln92_fu_485_p1);
    add_ln_fu_489_p3 <= (trunc_ln92_fu_485_p1 & empty_reg_665);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    empty_10_fu_591_p1 <= fpga_test_DW_StateSpace_PWORK_DS_3_1_fu_132;
    empty_11_fu_595_p1 <= fpga_test_DW_StateSpace_PWORK_DS_3_2_fu_136;
    empty_12_fu_599_p1 <= fpga_test_DW_StateSpace_PWORK_DS_3_3_fu_140;
    empty_8_fu_530_p2 <= (icmp_ln9_2_fu_516_p2 or icmp_ln9_1_fu_510_p2);
    empty_9_fu_587_p1 <= fpga_test_DW_StateSpace_PWORK_DS_3_fu_128;
    empty_fu_469_p1 <= i_fu_124(1 - 1 downto 0);
    fpga_test_DW_StateSpace_PWORK_DS_0_fu_536_p3 <= 
        select_ln9_1_i_fu_522_p3 when (empty_8_fu_530_p2(0) = '1') else 
        select_ln9_fu_502_p3;
    icmp_ln90_fu_457_p2 <= "1" when (i_fu_124 = ap_const_lv2_2) else "0";
    icmp_ln91_fu_473_p2 <= "1" when (j_reg_418 = ap_const_lv2_2) else "0";
    icmp_ln9_1_fu_510_p2 <= "1" when (add_ln_fu_489_p3 = ap_const_lv2_1) else "0";
    icmp_ln9_2_fu_516_p2 <= "1" when (add_ln_fu_489_p3 = ap_const_lv2_2) else "0";
    icmp_ln9_fu_496_p2 <= "1" when (add_ln_fu_489_p3 = ap_const_lv2_0) else "0";
    p_fpga_test_B_AC <= ap_const_lv32_0;

    p_fpga_test_B_AC_ap_vld_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_B_AC_ap_vld <= ap_const_logic_1;
        else 
            p_fpga_test_B_AC_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_B_DataTypeConversion1 <= ap_const_lv8_0;

    p_fpga_test_B_DataTypeConversion1_ap_vld_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_B_DataTypeConversion1_ap_vld <= ap_const_logic_1;
        else 
            p_fpga_test_B_DataTypeConversion1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_B_DataTypeConversion2 <= ap_const_lv64_0;

    p_fpga_test_B_DataTypeConversion2_ap_vld_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_B_DataTypeConversion2_ap_vld <= ap_const_logic_1;
        else 
            p_fpga_test_B_DataTypeConversion2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_B_Derivative <= ap_const_lv64_0;

    p_fpga_test_B_Derivative_ap_vld_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_B_Derivative_ap_vld <= ap_const_logic_1;
        else 
            p_fpga_test_B_Derivative_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_B_IC <= ap_const_lv64_0;

    p_fpga_test_B_IC_ap_vld_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_B_IC_ap_vld <= ap_const_logic_1;
        else 
            p_fpga_test_B_IC_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_B_LookUpTable <= ap_const_lv64_0;

    p_fpga_test_B_LookUpTable_ap_vld_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_B_LookUpTable_ap_vld <= ap_const_logic_1;
        else 
            p_fpga_test_B_LookUpTable_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_B_StateSpace_o1_address0 <= ap_const_lv64_1(1 - 1 downto 0);
    p_fpga_test_B_StateSpace_o1_address1 <= ap_const_lv64_0(1 - 1 downto 0);

    p_fpga_test_B_StateSpace_o1_ce0_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_B_StateSpace_o1_ce0 <= ap_const_logic_1;
        else 
            p_fpga_test_B_StateSpace_o1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    p_fpga_test_B_StateSpace_o1_ce1_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_B_StateSpace_o1_ce1 <= ap_const_logic_1;
        else 
            p_fpga_test_B_StateSpace_o1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_B_StateSpace_o1_d0 <= ap_const_lv64_0;
    p_fpga_test_B_StateSpace_o1_d1 <= ap_const_lv64_0;

    p_fpga_test_B_StateSpace_o1_we0_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_B_StateSpace_o1_we0 <= ap_const_logic_1;
        else 
            p_fpga_test_B_StateSpace_o1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    p_fpga_test_B_StateSpace_o1_we1_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_B_StateSpace_o1_we1 <= ap_const_logic_1;
        else 
            p_fpga_test_B_StateSpace_o1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_B_StateSpace_o2 <= ap_const_lv64_0;

    p_fpga_test_B_StateSpace_o2_ap_vld_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_B_StateSpace_o2_ap_vld <= ap_const_logic_1;
        else 
            p_fpga_test_B_StateSpace_o2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_DW_DelayTs_DSTATE <= ap_const_lv64_0;

    p_fpga_test_DW_DelayTs_DSTATE_ap_vld_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_DW_DelayTs_DSTATE_ap_vld <= ap_const_logic_1;
        else 
            p_fpga_test_DW_DelayTs_DSTATE_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_DW_DelayTs_DSTATE_f <= ap_const_lv64_0;

    p_fpga_test_DW_DelayTs_DSTATE_f_ap_vld_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_DW_DelayTs_DSTATE_f_ap_vld <= ap_const_logic_1;
        else 
            p_fpga_test_DW_DelayTs_DSTATE_f_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_DW_IC_FirstOutputTime <= ap_const_lv64_0;

    p_fpga_test_DW_IC_FirstOutputTime_ap_vld_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_DW_IC_FirstOutputTime_ap_vld <= ap_const_logic_1;
        else 
            p_fpga_test_DW_IC_FirstOutputTime_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_DW_LastUAtTimeA <= ap_const_lv64_0;

    p_fpga_test_DW_LastUAtTimeA_ap_vld_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_DW_LastUAtTimeA_ap_vld <= ap_const_logic_1;
        else 
            p_fpga_test_DW_LastUAtTimeA_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_DW_LastUAtTimeB <= ap_const_lv64_0;

    p_fpga_test_DW_LastUAtTimeB_ap_vld_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_DW_LastUAtTimeB_ap_vld <= ap_const_logic_1;
        else 
            p_fpga_test_DW_LastUAtTimeB_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_fpga_test_DW_StateSpace_IWORK_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_DW_StateSpace_IWORK_address0 <= ap_const_lv64_9(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            p_fpga_test_DW_StateSpace_IWORK_address0 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            p_fpga_test_DW_StateSpace_IWORK_address0 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            p_fpga_test_DW_StateSpace_IWORK_address0 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            p_fpga_test_DW_StateSpace_IWORK_address0 <= ap_const_lv64_2(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            p_fpga_test_DW_StateSpace_IWORK_address0 <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            p_fpga_test_DW_StateSpace_IWORK_address0 <= "XXXX";
        end if; 
    end process;


    p_fpga_test_DW_StateSpace_IWORK_address1_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_DW_StateSpace_IWORK_address1 <= ap_const_lv64_A(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            p_fpga_test_DW_StateSpace_IWORK_address1 <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            p_fpga_test_DW_StateSpace_IWORK_address1 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            p_fpga_test_DW_StateSpace_IWORK_address1 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            p_fpga_test_DW_StateSpace_IWORK_address1 <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            p_fpga_test_DW_StateSpace_IWORK_address1 <= "XXXX";
        end if; 
    end process;


    p_fpga_test_DW_StateSpace_IWORK_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            p_fpga_test_DW_StateSpace_IWORK_ce0 <= ap_const_logic_1;
        else 
            p_fpga_test_DW_StateSpace_IWORK_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    p_fpga_test_DW_StateSpace_IWORK_ce1_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            p_fpga_test_DW_StateSpace_IWORK_ce1 <= ap_const_logic_1;
        else 
            p_fpga_test_DW_StateSpace_IWORK_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_DW_StateSpace_IWORK_d0 <= ap_const_lv32_0;
    p_fpga_test_DW_StateSpace_IWORK_d1 <= ap_const_lv32_0;

    p_fpga_test_DW_StateSpace_IWORK_we0_assign_proc : process(ap_CS_fsm_state2, icmp_ln90_fu_457_p2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or ((icmp_ln90_fu_457_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            p_fpga_test_DW_StateSpace_IWORK_we0 <= ap_const_logic_1;
        else 
            p_fpga_test_DW_StateSpace_IWORK_we0 <= ap_const_logic_0;
        end if; 
    end process;


    p_fpga_test_DW_StateSpace_IWORK_we1_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            p_fpga_test_DW_StateSpace_IWORK_we1 <= ap_const_logic_1;
        else 
            p_fpga_test_DW_StateSpace_IWORK_we1 <= ap_const_logic_0;
        end if; 
    end process;

        p_fpga_test_DW_StateSpace_PWORK <= std_logic_vector(IEEE.numeric_std.resize(signed(p_partset_fu_603_p6),832));


    p_fpga_test_DW_StateSpace_PWORK_ap_vld_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_DW_StateSpace_PWORK_ap_vld <= ap_const_logic_1;
        else 
            p_fpga_test_DW_StateSpace_PWORK_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_DW_TimeStampA <= ap_const_lv64_0;

    p_fpga_test_DW_TimeStampA_ap_vld_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_DW_TimeStampA_ap_vld <= ap_const_logic_1;
        else 
            p_fpga_test_DW_TimeStampA_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_DW_TimeStampB <= ap_const_lv64_0;

    p_fpga_test_DW_TimeStampB_ap_vld_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_DW_TimeStampB_ap_vld <= ap_const_logic_1;
        else 
            p_fpga_test_DW_TimeStampB_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_DW_u5_Mode <= ap_const_lv8_0;

    p_fpga_test_DW_u5_Mode_ap_vld_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_DW_u5_Mode_ap_vld <= ap_const_logic_1;
        else 
            p_fpga_test_DW_u5_Mode_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_fpga_test_M <= ap_const_lv520_lc_1;

    p_fpga_test_M_ap_vld_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_fpga_test_M_ap_vld <= ap_const_logic_1;
        else 
            p_fpga_test_M_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_partset_fu_603_p6 <= ((((ap_const_lv545_lc_2 & empty_12_fu_599_p1) & empty_11_fu_595_p1) & empty_10_fu_591_p1) & empty_9_fu_587_p1);
    select_ln9_1_i_fu_522_p3 <= 
        ap_const_lv64_3FEFFFFDE7212F18 when (icmp_ln9_2_fu_516_p2(0) = '1') else 
        ap_const_lv64_3FEFFFFDE7212F19;
    select_ln9_fu_502_p3 <= 
        ap_const_lv64_BFEFFFFDE7212F19 when (icmp_ln9_fu_496_p2(0) = '1') else 
        ap_const_lv64_3EB0C6F6873C67ED;
    trunc_ln92_fu_485_p1 <= j_reg_418(1 - 1 downto 0);
end behav;
